GRANT CREATE SESSION, RESOURCE TO c##testuser;

GRANT CREATE ANY TABLE, SELECT ANY TABLE, INSERT ANY TABLE, DELETE ANY TABLE, DROP ANY TABLE, UPDATE ANY TABLE TO c##testuser;

GRANT CREATE ANY PROCEDURE, ALTER ANY PROCEDURE, EXECUTE ANY PROCEDURE TO c##testuser;

GRANT CREATE ANY SEQUENCE, SELECT ANY SEQUENCE TO c##testuser;

GRANT CREATE ANY SYNONYM TO c##testuser;